Part1 Denis Strizhkin
ok-technopolis-autumn-2022/Denis_Strizhkin pull request #1
Opened 2022-09-30 15:35 UTC by denisstrizhkin

2022-09-30 16:06 UTC, fromanywhere requested changes
Неплохо, хотя я бы не делал названия элементов заголовками второго уровня

После того, как поправите замечания, оставьте, пожалуйста, PR открытым, после следующей лекции будем вносить правки прямо сюда

2022-09-30 16:06 UTC, fromanywhere commented on index.html
> +        <div class="menu__list">
Здесь лучше подумать о другом теге

2022-09-30 16:06 UTC, fromanywhere commented on index.html
> +                <h2 class="todo-item__text">HTML</h2>
потерялась кнопка на удаление

2022-09-30 16:06 UTC, fromanywhere commented on index.html
> +                <span class="icon-ArrowDown"></span>
странно, а почему тут вдруг нейминг в другой методологии?

2022-09-30 17:27 UTC, denisstrizhkin commented
Исправил

2022-10-11 12:28 UTC, denisstrizhkin commented
Выполнил 2ое домашнее задание.

2022-10-11 14:59 UTC, fromanywhere commented
Так у Вас еще 1ое не принято

2022-10-11 15:02 UTC, fromanywhere requested changes

2022-10-11 15:02 UTC, fromanywhere commented on index.html
> +                        aria-label="Open dropdown menu"
тут лучше title, чтобы люди без скринридера тоже что-то поняли

2022-10-11 15:02 UTC, fromanywhere commented on index.html
> +                <div class="bottom__selectors">
тут нужно помочь скринридеру объяснить, что это один фильтр с переключателями. Предлагается role="radiogroup" и заголовок в aria-label

2022-10-11 15:02 UTC, fromanywhere commented on index.html
> +                    <button
На лекции договорились, что это радиокнопки

2022-10-11 15:02 UTC, fromanywhere commented on index.html
> +                        aria-label="Clear completed"
Нет смысла дублировать текст кнопки, скринридер его и так зачитает

2022-10-12 20:22 UTC, denisstrizhkin commented
Сделал исправления

2022-10-13 08:05 UTC, fromanywhere approved these changes

2022-10-13 14:28 UTC, merged